version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./web
    ports: 
      - 3000:4173
    volumes:
      - ./web:/app_frontend
    depends_on:
      - backend
  backend:
    container_name: api_backend
    build: ./server
    ports: 
      - 3001:3001
    environment:
      - PORT=3001
      - DATABASE_URL=mysql://root:123456@localhost:3302/database
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsoft", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    volumes:
      - ./server:/app_backend
  database:
    image: mysql:8.0.21
    container_name: database
    ports:
      - 3002:3302
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
